export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const BEGIN_AJAX_ERROR = 'BEGIN_AJAX_ERROR';
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const URL ='http://ec2-18-223-102-201.us-east-2.compute.amazonaws.com:7000/api/customers/';